// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNNBhD1awLh1csGAjW_Nl4KpStk_yk-8g',
    appId: '1:775106421186:web:3fec1cd77e687c7316365b',
    messagingSenderId: '775106421186',
    projectId: 'customerbook-d8981',
    authDomain: 'customerbook-d8981.firebaseapp.com',
    storageBucket: 'customerbook-d8981.appspot.com',
    measurementId: 'G-0T4D6XFR58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSuAOK_tGOM-XWHIkAuW5fZ-kfhfDfRe8',
    appId: '1:775106421186:android:bd2babe635b7316216365b',
    messagingSenderId: '775106421186',
    projectId: 'customerbook-d8981',
    storageBucket: 'customerbook-d8981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4J9CEzEwqUnxklQMKxk8fjT8n_tSQlxQ',
    appId: '1:775106421186:ios:cbefeaaf2a0b9dfb16365b',
    messagingSenderId: '775106421186',
    projectId: 'customerbook-d8981',
    storageBucket: 'customerbook-d8981.appspot.com',
    iosClientId: '775106421186-3ftpc79umhj645ncdcrrell8gk11j6ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.customermanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4J9CEzEwqUnxklQMKxk8fjT8n_tSQlxQ',
    appId: '1:775106421186:ios:cbefeaaf2a0b9dfb16365b',
    messagingSenderId: '775106421186',
    projectId: 'customerbook-d8981',
    storageBucket: 'customerbook-d8981.appspot.com',
    iosClientId: '775106421186-3ftpc79umhj645ncdcrrell8gk11j6ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.customermanager',
  );
}
